export interface PracticeTopic {
  id: string;
  code: string;
  name: string;
  subjectCode: "QUANT" | "REASONING" | "ENGLISH" | "GA_BANKING" | "COMPUTER";
  subjectName: string;
  category: string;
  difficulty: "EASY" | "MEDIUM" | "HARD" | "MIXED";
  prelimsWeightage: string;
  description: string;
  tags: string[];
}

export interface PracticeQuestion {
  id: string;
  topicCode: string;
  subjectCode: string;
  text: string;
  options: string[];
  correctOptionIndex: number;
  explanation: string;
  shortcut?: string;
  commonTrap?: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  source: string;
}

export const BANKING_SUBJECTS = [
  {
    code: "QUANT",
    name: "Quantitative Aptitude",
    icon: "Calculator",
    description: "Speed arithmetic, algebra, number series & high-level data interpretation.",
    totalTopics: 17,
  },
  {
    code: "REASONING",
    name: "Reasoning Ability",
    icon: "Brain",
    description: "Puzzles, seating arrangements, syllogisms & logical deductions.",
    totalTopics: 16,
  },
  {
    code: "ENGLISH",
    name: "English Language",
    icon: "BookOpen",
    description: "Reading comprehension, grammar mechanics, vocab & sentence structuring.",
    totalTopics: 10,
  },
  {
    code: "GA_BANKING",
    name: "General & Banking Awareness",
    icon: "Landmark",
    description: "RBI policies, financial terms, current affairs & static banking awareness.",
    totalTopics: 10,
  },
  {
    code: "COMPUTER",
    name: "Computer Aptitude",
    icon: "Cpu",
    description: "Hardware, networking, DBMS, cyber security & keyboard shortcuts.",
    totalTopics: 5,
  },
] as const;

export const ALL_BANKING_TOPICS: PracticeTopic[] = [
  // 📐 QUANTITATIVE APTITUDE (17 Topics)
  {
    id: "q1",
    code: "SIMPLIFICATION",
    name: "Simplification & Approximation",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Speed Math",
    difficulty: "EASY",
    prelimsWeightage: "10-15 Qs",
    description: "BODMAS rule, percentage conversion, surds & indices, square and cube roots.",
    tags: ["BODMAS", "Squares/Cubes", "Percentage Table"],
  },
  {
    id: "q2",
    code: "QUADRATIC_EQUATIONS",
    name: "Quadratic Equations & Polynomials",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Algebra",
    difficulty: "EASY",
    prelimsWeightage: "5 Qs",
    description: "Root sign methods, coefficient factorization, relationship comparison (x > y, x < y, x ≥ y, x ≤ y, CND).",
    tags: ["Sign Table Shortcut", "Roots Comparison", "Inequalities"],
  },
  {
    id: "q3",
    code: "MISSING_NUMBER_SERIES",
    name: "Missing Number Series",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Speed Math",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "Difference series, double difference, geometric multiplication (×0.5, ×1.5), alternating cubes.",
    tags: ["Double Difference", "Prime Steps", "Fractional Multipliers"],
  },
  {
    id: "q4",
    code: "WRONG_NUMBER_SERIES",
    name: "Wrong Number Series",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Speed Math",
    difficulty: "HARD",
    prelimsWeightage: "5 Qs",
    description: "Identifying flawed terms in multiplication, alternating operations, square and cubic pattern series.",
    tags: ["Pattern Validation", "Subtractions", "Series Faults"],
  },
  {
    id: "q5",
    code: "DI_BAR_GRAPH",
    name: "Data Interpretation — Bar Graph",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Data Interpretation",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "Comparative bar charts, stacked bars, year-on-year growth percentage calculations.",
    tags: ["Stacked Bars", "YoY Growth", "Averages"],
  },
  {
    id: "q6",
    code: "DI_PIE_CHART",
    name: "Data Interpretation — Pie Chart",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Data Interpretation",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "Single and dual pie charts, degree to percentage conversion (360° = 100%), distribution ratios.",
    tags: ["Degrees to Pct", "Dual Pie", "Ratio Analysis"],
  },
  {
    id: "q7",
    code: "DI_TABLE_CHART",
    name: "Data Interpretation — Table Chart",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Data Interpretation",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "Multi-column data extraction, ratio comparisons, percentage differences, and fast row aggregation.",
    tags: ["Cross-Tabulation", "Difference Tables", "Missing Cells"],
  },
  {
    id: "q8",
    code: "DI_CASELET",
    name: "Data Interpretation — Caselet & Radar",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Data Interpretation",
    difficulty: "HARD",
    prelimsWeightage: "5 Qs",
    description: "Venn-diagram based paragraph data, multi-variable equation formulation, spider/radar web charts.",
    tags: ["Venn Diagrams", "Paragraph DI", "Equation Setup"],
  },
  {
    id: "q9",
    code: "PROFIT_LOSS",
    name: "Profit, Loss & Discount",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Arithmetic",
    difficulty: "MEDIUM",
    prelimsWeightage: "2-3 Qs",
    description: "Cost price, marked price, successive discounts, dishonest dealer false weight scenarios.",
    tags: ["Net Change", "Dishonest Dealer", "Successive Discounts"],
  },
  {
    id: "q10",
    code: "SI_CI",
    name: "Simple & Compound Interest",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Arithmetic",
    difficulty: "MEDIUM",
    prelimsWeightage: "1-2 Qs",
    description: "Compound annual vs semi-annual rates, 2-year and 3-year difference formula, installments.",
    tags: ["Rate Trees", "Difference Formulas", "Equal Installments"],
  },
  {
    id: "q11",
    code: "TIME_SPEED_DISTANCE",
    name: "Time, Speed & Distance / Trains & Boats",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Arithmetic",
    difficulty: "HARD",
    prelimsWeightage: "2-3 Qs",
    description: "Relative speed, crossing poles/platforms, upstream and downstream river currents, circular tracks.",
    tags: ["Relative Speed", "Upstream/Downstream", "Train Crossings"],
  },
  {
    id: "q12",
    code: "TIME_WORK",
    name: "Time & Work / Pipes & Cisterns",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Arithmetic",
    difficulty: "MEDIUM",
    prelimsWeightage: "2-3 Qs",
    description: "LCM efficiency method, wages distribution, alternating working days, negative leak rates.",
    tags: ["Efficiency Ratios", "Alternating Hours", "Leak Rates"],
  },
  {
    id: "q13",
    code: "RATIO_PROPORTION",
    name: "Ratio & Proportion / Partnership",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Arithmetic",
    difficulty: "EASY",
    prelimsWeightage: "2 Qs",
    description: "Compound ratios, mean proportion, active vs sleeping partner capital-time investment allocation.",
    tags: ["Capital x Time", "Mean Proportional", "Dividends"],
  },
  {
    id: "q14",
    code: "MIXTURE_ALLIGATION",
    name: "Mixture & Alligation",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Arithmetic",
    difficulty: "MEDIUM",
    prelimsWeightage: "1-2 Qs",
    description: "Cross rule of alligation, repeated replacement formula [x(1 - y/x)^n], mixing alloy proportions.",
    tags: ["Alligation Cross", "Replacement Formula", "Concentrations"],
  },
  {
    id: "q15",
    code: "AGES_AVERAGES",
    name: "Ages & Averages",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Arithmetic",
    difficulty: "EASY",
    prelimsWeightage: "1-2 Qs",
    description: "Weighted averages, deviation method, past and future age ratio equations.",
    tags: ["Deviation Method", "Age Shifting", "Group Replacement"],
  },
  {
    id: "q16",
    code: "PROBABILITY",
    name: "Permutations, Combinations & Probability",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Arithmetic",
    difficulty: "HARD",
    prelimsWeightage: "1-2 Qs",
    description: "Card deck selection, colored marble urns, vowel seating constraints, conditional probability.",
    tags: ["Arrangements", "Selection (nCr)", "At least one"],
  },
  {
    id: "q17",
    code: "MENSURATION",
    name: "Mensuration 2D & 3D",
    subjectCode: "QUANT",
    subjectName: "Quantitative Aptitude",
    category: "Arithmetic",
    difficulty: "MEDIUM",
    prelimsWeightage: "1-2 Qs",
    description: "Circumference, sector area, cylinder/cone/sphere volume conversion, wire bending into shapes.",
    tags: ["Surface Area", "Volume Equivalence", "Perimeter Ratios"],
  },

  // 🧩 REASONING ABILITY (16 Topics)
  {
    id: "r1",
    code: "SYLLOGISM",
    name: "Syllogism (Only / A Few, Possibility)",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Deductive Logic",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "Modern banking syllogism patterns: Only a few, Some not, Possibility cases, Either/Or conditions.",
    tags: ["Only a few", "Possibility Venn", "Either/Or"],
  },
  {
    id: "r2",
    code: "INEQUALITIES",
    name: "Inequality (Direct & Coded)",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Deductive Logic",
    difficulty: "EASY",
    prelimsWeightage: "5 Qs",
    description: "Open gate / closed gate technique, coded symbol inequality decoding, combined chain comparisons.",
    tags: ["Gate Method", "Coded Symbols", "Chain Linking"],
  },
  {
    id: "r3",
    code: "CIRCULAR_SEATING",
    name: "Circular Seating Arrangement (In/Out)",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Puzzles",
    difficulty: "HARD",
    prelimsWeightage: "5 Qs",
    description: "8 to 10 persons sitting facing inside/outside with variable attributes (fruits, colors, professions).",
    tags: ["Bidirectional Facing", "Attribute Binding", "Case Elimination"],
  },
  {
    id: "r4",
    code: "LINEAR_SEATING",
    name: "Linear Seating (Parallel Rows / North-South)",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Puzzles",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "Parallel 2 rows (North and South facing persons), uncertain number of persons in a single row.",
    tags: ["Parallel Rows", "Uncertain Number", "Facing Coordinates"],
  },
  {
    id: "r5",
    code: "SQUARE_RECTANGULAR_SEATING",
    name: "Square & Rectangular Seating",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Puzzles",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "Corner persons facing outward, middle edge persons facing inward, table placement logic.",
    tags: ["Corner vs Middle", "Perimeter Positions", "Dual Cases"],
  },
  {
    id: "r6",
    code: "FLOOR_FLAT_PUZZLES",
    name: "Floor & Flat Puzzles",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Puzzles",
    difficulty: "HARD",
    prelimsWeightage: "5 Qs",
    description: "Multi-storey building floors (1 to 8) with Flat A & Flat B, directional and floor gap constraints.",
    tags: ["Flat Matrix", "Odd/Even Floors", "Vacant Flats"],
  },
  {
    id: "r7",
    code: "BOX_PUZZLES",
    name: "Box & Matrix Puzzles",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Puzzles",
    difficulty: "HARD",
    prelimsWeightage: "5 Qs",
    description: "7 to 10 boxes stacked vertically with color/weight attributes and relative position offsets.",
    tags: ["Stack Stacking", "Top/Bottom Gaps", "Variable Attributes"],
  },
  {
    id: "r8",
    code: "MONTH_DATE_PUZZLES",
    name: "Month & Date Scheduling Puzzles",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Puzzles",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "People giving seminars on 12th & 27th across March, April, May, June (30 vs 31 day month counts).",
    tags: ["30 vs 31 Days", "Dual Dates", "Chronology Table"],
  },
  {
    id: "r9",
    code: "BLOOD_RELATIONS",
    name: "Blood Relations (Family Tree & Coded)",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Analytical",
    difficulty: "EASY",
    prelimsWeightage: "3 Qs",
    description: "3-generation family tree diagrams, paternal vs maternal uncles, coded relations (A + B means A is father of B).",
    tags: ["Family Tree", "Gender Signs", "Coded Symbols"],
  },
  {
    id: "r10",
    code: "DIRECTION_DISTANCE",
    name: "Direction & Distance",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Analytical",
    difficulty: "EASY",
    prelimsWeightage: "3 Qs",
    description: "Pythagoras theorem displacement, shadow at sunrise/sunset, coded point coordinate directions.",
    tags: ["Pythagoras", "Shadow Logic", "Cartesian Movement"],
  },
  {
    id: "r11",
    code: "CODING_DECODING",
    name: "Coding-Decoding (Chinese & New Pattern)",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Analytical",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "Substitutional sentence coding elimination, symbol-letter-number logic based on vowel count and word length.",
    tags: ["Word Elimination", "Vowel Rules", "Reverse Alphabet Ranks"],
  },
  {
    id: "r12",
    code: "INPUT_OUTPUT",
    name: "Input-Output (Machine Arrangement)",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Mains Special",
    difficulty: "HARD",
    prelimsWeightage: "5 Qs (Mains)",
    description: "Step-by-step sorting of numbers and words based on alphabetical order, odd/even transformations.",
    tags: ["Step Trace", "Left-Right Shifting", "Mathematical Operation Steps"],
  },
  {
    id: "r13",
    code: "ORDER_RANKING",
    name: "Order & Ranking / Alphabetical Series",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Analytical",
    difficulty: "EASY",
    prelimsWeightage: "3-5 Qs",
    description: "Left/right rank formula (Total = L + R - 1), position swapping, alphanumeric symbol string counting.",
    tags: ["Total = L+R-1", "Alphanumeric Drop", "Interchange Ranks"],
  },
  {
    id: "r14",
    code: "CRITICAL_REASONING",
    name: "Critical & Logical Reasoning",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Mains Special",
    difficulty: "HARD",
    prelimsWeightage: "6-8 Qs (Mains)",
    description: "Statement & Assumption, Cause & Effect, Statement & Course of Action, Strong vs Weak Arguments.",
    tags: ["Assumptions", "Cause-Effect", "Course of Action"],
  },
  {
    id: "r15",
    code: "DATA_SUFFICIENCY_REAS",
    name: "Data Sufficiency (Reasoning)",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Analytical",
    difficulty: "HARD",
    prelimsWeightage: "5 Qs",
    description: "Determining whether Statement I alone, Statement II alone, or both combined are sufficient to answer.",
    tags: ["Statement I vs II", "Either/Or Sufficiency", "Unique Answer Test"],
  },
  {
    id: "r16",
    code: "DESIGNATION_PUZZLE",
    name: "Designation & Hierarchy Puzzles",
    subjectCode: "REASONING",
    subjectName: "Reasoning Ability",
    category: "Puzzles",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "Hierarchical ranking (CMD > ED > CGM > GM > DGM > Manager > AM > Clerk) and matching assignments.",
    tags: ["Seniority Order", "Rank Constraints", "Dual Attributes"],
  },

  // 📖 ENGLISH LANGUAGE (10 Topics)
  {
    id: "e1",
    code: "READING_COMPREHENSION",
    name: "Reading Comprehension (Economy & Tech)",
    subjectCode: "ENGLISH",
    subjectName: "English Language",
    category: "Comprehension",
    difficulty: "MEDIUM",
    prelimsWeightage: "8-10 Qs",
    description: "Editorial passages on macroeconomics, RBI banking reforms, inference questions, tone of author, contextual vocabulary.",
    tags: ["Inference", "Tone of Passage", "Contextual Antonyms"],
  },
  {
    id: "e2",
    code: "CLOZE_TEST",
    name: "Cloze Test",
    subjectCode: "ENGLISH",
    subjectName: "English Language",
    category: "Comprehension",
    difficulty: "MEDIUM",
    prelimsWeightage: "5-6 Qs",
    description: "Blanks in connected paragraphs testing collocation, prepositional phrases, and grammatical tense flow.",
    tags: ["Context Clues", "Preposition Pairs", "Collocations"],
  },
  {
    id: "e3",
    code: "ERROR_SPOTTING",
    name: "Error Spotting & Sentence Correction",
    subjectCode: "ENGLISH",
    subjectName: "English Language",
    category: "Grammar",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "Subject-verb agreement, parallelism, conditional tenses, misplaced modifiers, preposition errors.",
    tags: ["Subject-Verb", "Parallelism", "Conditional Clauses"],
  },
  {
    id: "e4",
    code: "PARA_JUMBLES",
    name: "Para Jumbles & Sentence Rearrangement",
    subjectCode: "ENGLISH",
    subjectName: "English Language",
    category: "Structure",
    difficulty: "HARD",
    prelimsWeightage: "5 Qs",
    description: "Finding mandatory pairs, identifying the introductory thematic sentence, pronoun antecedent links.",
    tags: ["Mandatory Pairs", "Pronoun Links", "Introductory Sentence"],
  },
  {
    id: "e5",
    code: "FILLERS",
    name: "Fillers (Single, Double & Column)",
    subjectCode: "ENGLISH",
    subjectName: "English Language",
    category: "Vocabulary",
    difficulty: "EASY",
    prelimsWeightage: "5 Qs",
    description: "Selecting words that satisfy both grammatical form and sentence semantics in single and dual blanks.",
    tags: ["Double Blanks", "Grammar Agreement", "Connotations"],
  },
  {
    id: "e6",
    code: "PHRASE_REPLACEMENT",
    name: "Phrase Replacement & Idioms",
    subjectCode: "ENGLISH",
    subjectName: "English Language",
    category: "Grammar",
    difficulty: "MEDIUM",
    prelimsWeightage: "4-5 Qs",
    description: "Correcting bold phrases with idiomatic English, phrasal verbs, and proper preposition usage.",
    tags: ["Phrasal Verbs", "Idioms", "Grammar Tense"],
  },
  {
    id: "e7",
    code: "WORD_SWAP",
    name: "Word Swap & Word Usage",
    subjectCode: "ENGLISH",
    subjectName: "English Language",
    category: "Vocabulary",
    difficulty: "EASY",
    prelimsWeightage: "4-5 Qs",
    description: "Swapping bold words (A, B, C, D) across sentences to make the sentence contextually and grammatically correct.",
    tags: ["Word Positioning", "Contextual Fits", "Part of Speech"],
  },
  {
    id: "e8",
    code: "MATCH_COLUMNS",
    name: "Match the Columns (Sentence Connectors)",
    subjectCode: "ENGLISH",
    subjectName: "English Language",
    category: "Structure",
    difficulty: "MEDIUM",
    prelimsWeightage: "4-5 Qs",
    description: "Connecting Column 1 halves (A, B, C) with Column 2 halves (D, E, F) to form meaningful compound sentences.",
    tags: ["Sentence Connectors", "Cohesion", "Syntax Check"],
  },
  {
    id: "e9",
    code: "SENTENCE_IMPROVEMENT",
    name: "Sentence Improvement",
    subjectCode: "ENGLISH",
    subjectName: "English Language",
    category: "Grammar",
    difficulty: "EASY",
    prelimsWeightage: "4-5 Qs",
    description: "Re-writing underlined segments for conciseness, correct tense, and active voice precision.",
    tags: ["Conciseness", "Tense Consistency", "No Correction Required"],
  },
  {
    id: "e10",
    code: "CONNECTORS_STARTERS",
    name: "Sentence Connectors & Starters",
    subjectCode: "ENGLISH",
    subjectName: "English Language",
    category: "Mains Special",
    difficulty: "HARD",
    prelimsWeightage: "4 Qs (Mains)",
    description: "Combining two discrete sentences using words like 'Although', 'Notwithstanding', 'In addition to', 'Lest'.",
    tags: ["Conjunctions", "Complex Sentences", "Contrast Starters"],
  },

  // 🏦 GENERAL & BANKING AWARENESS (10 Topics)
  {
    id: "g1",
    code: "BANKING_TERMS",
    name: "Banking Terminology & Monetary Policy",
    subjectCode: "GA_BANKING",
    subjectName: "General & Banking Awareness",
    category: "Banking Concepts",
    difficulty: "EASY",
    prelimsWeightage: "6-8 Qs (Mains)",
    description: "Repo rate, Reverse Repo, SDF, MSF, CRR, SLR, Open Market Operations, Liquidity Adjustment Facility.",
    tags: ["RBI Rates", "Monetary Policy", "Liquidity Tools"],
  },
  {
    id: "g2",
    code: "RBI_CIRCULARS",
    name: "RBI Notifications, Circulars & Master Directions",
    subjectCode: "GA_BANKING",
    subjectName: "General & Banking Awareness",
    category: "Banking Concepts",
    difficulty: "HARD",
    prelimsWeightage: "8-10 Qs (Mains)",
    description: "Priority Sector Lending (PSL) targets, Basel III Capital Adequacy, PCA framework, Digital Payment Directives.",
    tags: ["PSL Norms", "Basel III", "Prompt Corrective Action"],
  },
  {
    id: "g3",
    code: "CURRENT_AFFAIRS_BANKING",
    name: "Monthly Current Affairs (National & Banking)",
    subjectCode: "GA_BANKING",
    subjectName: "General & Banking Awareness",
    category: "Current Affairs",
    difficulty: "MEDIUM",
    prelimsWeightage: "12-15 Qs (Mains)",
    description: "Bank mergers, MoU signings, appointments of MD/CEOs, international banking summits, awards.",
    tags: ["MoUs", "Appointments", "Bank Initiatives"],
  },
  {
    id: "g4",
    code: "UNION_BUDGET_SURVEY",
    name: "Union Budget & Economic Survey",
    subjectCode: "GA_BANKING",
    subjectName: "General & Banking Awareness",
    category: "Economy",
    difficulty: "HARD",
    prelimsWeightage: "5-6 Qs (Mains)",
    description: "Fiscal deficit targets, key sectoral allocations (Agriculture, MSME, Infrastructure), GDP growth forecasts.",
    tags: ["Fiscal Deficit", "Tax Slabs", "Budget Allocations"],
  },
  {
    id: "g5",
    code: "GOVT_SCHEMES",
    name: "Government Schemes & Financial Inclusion",
    subjectCode: "GA_BANKING",
    subjectName: "General & Banking Awareness",
    category: "Government Policies",
    difficulty: "MEDIUM",
    prelimsWeightage: "6-8 Qs (Mains)",
    description: "PM Jan Dhan Yojana, PMJJBY, PMSBY, APY, PM SVANidhi, Mudra loans (Shishu, Kishore, Tarun limits).",
    tags: ["PMJDY", "Insurance Limits", "Mudra Limits"],
  },
  {
    id: "g6",
    code: "NPA_IBC",
    name: "NPA Resolution, SARFAESI & IBC 2016",
    subjectCode: "GA_BANKING",
    subjectName: "General & Banking Awareness",
    category: "Banking Concepts",
    difficulty: "HARD",
    prelimsWeightage: "4-5 Qs (Mains)",
    description: "Special Mention Accounts (SMA-0, SMA-1, SMA-2), Bad Bank / NARCL, NCLT resolution processes.",
    tags: ["SMA Classification", "NARCL", "SARFAESI Act"],
  },
  {
    id: "g7",
    code: "INT_ORGANIZATIONS",
    name: "International Financial Organizations & HQs",
    subjectCode: "GA_BANKING",
    subjectName: "General & Banking Awareness",
    category: "Static GK",
    difficulty: "EASY",
    prelimsWeightage: "3-4 Qs (Mains)",
    description: "World Bank, IMF, ADB, NDB, BIS, FATF headquarters, current chiefs, member countries.",
    tags: ["IMF", "World Bank", "ADB Headquarters"],
  },
  {
    id: "g8",
    code: "PAYMENT_SYSTEMS",
    name: "Digital Payment Systems (UPI, NEFT, RTGS, CBDC)",
    subjectCode: "GA_BANKING",
    subjectName: "General & Banking Awareness",
    category: "Fintech & Banking",
    difficulty: "EASY",
    prelimsWeightage: "4-5 Qs (Mains)",
    description: "NPCI infrastructure (UPI, IMPS, RuPay, NETC Fastag), e-Rupee CBDC architecture, transaction limits.",
    tags: ["NPCI", "e-Rupee CBDC", "NEFT vs RTGS"],
  },
  {
    id: "g9",
    code: "STATIC_GK_INDIA",
    name: "Static GK (National Parks, Dams, Power Plants)",
    subjectCode: "GA_BANKING",
    subjectName: "General & Banking Awareness",
    category: "Static GK",
    difficulty: "EASY",
    prelimsWeightage: "4-5 Qs (Mains)",
    description: "National parks, Tiger reserves, Major dams on rivers, Nuclear & Thermal power stations by state.",
    tags: ["National Parks", "Rivers & Dams", "Nuclear Plants"],
  },
  {
    id: "g10",
    code: "FINANCIAL_MARKETS",
    name: "Capital & Money Markets (SEBI, Treasury Bills, CP)",
    subjectCode: "GA_BANKING",
    subjectName: "General & Banking Awareness",
    category: "Banking Concepts",
    difficulty: "MEDIUM",
    prelimsWeightage: "4-5 Qs (Mains)",
    description: "Treasury Bills (91, 182, 364 days), Commercial Papers, Certificates of Deposit, SEBI regulations.",
    tags: ["T-Bills", "Commercial Paper", "SEBI Instruments"],
  },

  // 💻 COMPUTER APTITUDE (5 Topics)
  {
    id: "c1",
    code: "COMPUTER_HARDWARE",
    name: "Computer Hardware & Memory Architecture",
    subjectCode: "COMPUTER",
    subjectName: "Computer Aptitude",
    category: "Hardware",
    difficulty: "EASY",
    prelimsWeightage: "4 Qs",
    description: "ALU, Registers, Cache memory L1/L2/L3, RAM vs ROM, Secondary storage interfaces.",
    tags: ["Cache Memory", "CPU Registers", "ROM vs RAM"],
  },
  {
    id: "c2",
    code: "NETWORKING_OS",
    name: "Networking & OSI 7-Layer Model",
    subjectCode: "COMPUTER",
    subjectName: "Computer Aptitude",
    category: "Networking",
    difficulty: "MEDIUM",
    prelimsWeightage: "5 Qs",
    description: "OSI & TCP/IP layer protocols (HTTP, FTP, SMTP, DNS, DHCP), IPv4 vs IPv6 addressing, Subnets.",
    tags: ["OSI 7 Layers", "Port Numbers", "IPv4 vs IPv6"],
  },
  {
    id: "c3",
    code: "DBMS_SQL",
    name: "DBMS & SQL Fundamentals",
    subjectCode: "COMPUTER",
    subjectName: "Computer Aptitude",
    category: "Software",
    difficulty: "MEDIUM",
    prelimsWeightage: "4 Qs",
    description: "Primary key, foreign key, ER diagrams, Normalization (1NF, 2NF, 3NF, BCNF), Basic SQL queries.",
    tags: ["Keys", "Normalization", "SQL Joins"],
  },
  {
    id: "c4",
    code: "CYBER_SECURITY",
    name: "Cyber Security, Malware & Cryptography",
    subjectCode: "COMPUTER",
    subjectName: "Computer Aptitude",
    category: "Security",
    difficulty: "EASY",
    prelimsWeightage: "4 Qs",
    description: "Phishing, Ransomware, Trojan horse, Symmetric vs Asymmetric encryption, SSL/TLS handshake.",
    tags: ["Phishing", "Encryption", "Firewalls"],
  },
  {
    id: "c5",
    code: "MS_OFFICE_SHORTCUTS",
    name: "MS Office & Keyboard Shortcuts",
    subjectCode: "COMPUTER",
    subjectName: "Computer Aptitude",
    category: "Software",
    difficulty: "EASY",
    prelimsWeightage: "3 Qs",
    description: "MS Excel formulas (VLOOKUP, INDEX-MATCH), Word macros, universal shortcut keys.",
    tags: ["VLOOKUP", "Shortcuts", "PowerPoint"],
  },
];

export const TOPIC_QUESTION_BANK: Record<string, PracticeQuestion[]> = {
  SIMPLIFICATION: [
    {
      id: "SMP_001",
      topicCode: "SIMPLIFICATION",
      subjectCode: "QUANT",
      text: "What will come in place of the question mark (?) in the following expression?\n\n$$\\sqrt{784} \\times 15 + 45\\% \\text{ of } 800 - 12^2 = ?$$",
      options: ["636", "616", "646", "624", "652"],
      correctOptionIndex: 0,
      explanation: "Step 1: Calculate the square root: \\sqrt{784} = 28.\nStep 2: Multiply by 15: 28 \\times 15 = 420.\nStep 3: Calculate percentage: 45\\% \\text{ of } 800 = \\frac{45}{100} \\times 800 = 45 \\times 8 = 360.\nStep 4: Compute the square: 12^2 = 144.\nStep 5: Perform arithmetic operations according to BODMAS:\n? = 420 + 360 - 144\n? = 780 - 144 = 636.",
      shortcut: "Split multiplication: 28 \\times 15 = 28 \\times \\frac{30}{2} = 14 \\times 30 = 420. For 45\\%: 50\\% (400) - 5\\% (40) = 360.",
      commonTrap: "Ensure you evaluate 12² = 144 after adding (420 + 360 = 780) to avoid order-of-operation sign errors.",
      difficulty: "EASY",
      source: "Ace Quantitative Aptitude (2024)",
    },
    {
      id: "SMP_002",
      topicCode: "SIMPLIFICATION",
      subjectCode: "QUANT",
      text: "Find the approximate value of (?) in the following expression:\n\n$$24.98\\% \\text{ of } 639.92 + 33.33\\% \\text{ of } 899.85 - \\sqrt{624.89} = ?$$",
      options: ["435", "445", "425", "465", "415"],
      correctOptionIndex: 0,
      explanation: "Step 1: Round values to nearest integers: 25\\% \\text{ of } 640 + \\frac{1}{3} \\text{ of } 900 - \\sqrt{625}.\nStep 2: 25\\% (\\frac{1}{4}) \\times 640 = 160.\nStep 3: \\frac{1}{3} \\times 900 = 300.\nStep 4: \\sqrt{625} = 25.\nStep 5: ? = 160 + 300 - 25 = 460 - 25 = 435.",
      shortcut: "Use standard fraction conversion: 25\\% = 1/4 and 33.33\\% = 1/3.",
      commonTrap: "Do not calculate exact decimals; round aggressively to nearest integer in approximation.",
      difficulty: "EASY",
      source: "4000 Testbook Questions",
    },
    {
      id: "SMP_003",
      topicCode: "SIMPLIFICATION",
      subjectCode: "QUANT",
      text: "What will come in place of the question mark (?) in the following equation?\n\n$$28.314 - 31.427 + 113.928 = ? + 29.114$$",
      options: ["81.711", "80.701", "71.711", "81.701", "None of these"],
      correctOptionIndex: 3,
      explanation: "Step 1: Rearrange the equation to isolate (?):\n? = (28.314 + 113.928) - (31.427 + 29.114)\n\nStep 2: Add positive decimal terms:\n28.314 + 113.928 = 142.242\n\nStep 3: Add subtracted decimal terms:\n31.427 + 29.114 = 60.541\n\nStep 4: Perform final subtraction:\n? = 142.242 - 60.541 = 81.701.\n\nConclusion: Matches Option D: 81.701.",
      shortcut: "Group all positive values and all negative values before final decimal subtraction.",
      commonTrap: "Be careful not to confuse 81.701 with 81.711 due to column alignment.",
      difficulty: "EASY",
      source: "4000 Testbook Questions",
    },
    {
      id: "SMP_004",
      topicCode: "SIMPLIFICATION",
      subjectCode: "QUANT",
      text: "What approximate value should come in place of the question mark (?) in the following expression?\n\n$$78.143 - [5.08 + 3.15 \\text{ of } (24.98 - 1.95 \\times 9.998)] = ?$$",
      options: ["58", "78", "98", "118", "228"],
      correctOptionIndex: 0,
      explanation: "Step 1: Approximate terms inside innermost parentheses:\n24.98 - 1.95 \\times 9.998 \\approx 25 - (2 \\times 10) = 25 - 20 = 5.\n\nStep 2: Calculate 'of' multiplication:\n3.15 \\text{ of } 5 \\approx 3 \\times 5 = 15.\n\nStep 3: Evaluate terms inside the outer brackets:\n[5.08 + 15] \\approx 5 + 15 = 20.\n\nStep 4: Perform final subtraction:\n78.143 - 20 \\approx 78 - 20 = 58.\n\nConclusion: Matches Option A (58).",
      shortcut: "Work from innermost bracket outwards using whole numbers: (25 - 20 = 5) → (3 × 5 = 15) → (5 + 15 = 20) → 78 - 20 = 58.",
      commonTrap: "Remember BODMAS priority: 'of' and multiplication must be evaluated before bracket addition.",
      difficulty: "MEDIUM",
      source: "4000 Testbook Questions",
    },
    {
      id: "SMP_005",
      topicCode: "SIMPLIFICATION",
      subjectCode: "QUANT",
      text: "What approximate value should come in place of the question mark (?) in the following expression?\n\n$$1675.156 + 12.192 \\times 55.871 = ?$$",
      options: ["2933", "2840", "2347", "2271", "2155"],
      correctOptionIndex: 2,
      explanation: "Step 1: Round all values to nearest integers:\n1675.156 \\approx 1675\n12.192 \\approx 12\n55.871 \\approx 56\n\nStep 2: Perform multiplication first (BODMAS):\n12 \\times 56 = 12 \\times (50 + 6) = 600 + 72 = 672.\n\nStep 3: Perform addition:\n? \\approx 1675 + 672 = 2347.\n\nConclusion: Matches Option C (2347).",
      shortcut: "Split multiplication: 12 × 56 = 672. Then 1675 + 672 = 2347.",
      commonTrap: "Do not add 1675 + 12 before multiplying with 56; multiplication has higher precedence.",
      difficulty: "EASY",
      source: "4000 Testbook Questions",
    },
    {
      id: "SMP_006",
      topicCode: "SIMPLIFICATION",
      subjectCode: "QUANT",
      text: "What approximate value should come in place of the question mark (?) in the following expression?\n\n$$33.5\\% \\text{ of } 1924.2 + ?\\% \\text{ of } 5324.4 = 6827.586$$",
      options: ["136", "282", "90", "116", "199"],
      correctOptionIndex: 3,
      explanation: "Step 1: Round all numbers to practical calculation integers:\n33.5\\% \\approx \\frac{1}{3}\n1924.2 \\approx 1924\n5324.4 \\approx 5324\n6827.586 \\approx 6828\n\nStep 2: Calculate the first percentage term:\n33.5\\% \\text{ of } 1924.2 \\approx 0.335 \\times 1924.2 \\approx 645.\n\nStep 3: Subtract from total:\n?\\% \\text{ of } 5324 = 6828 - 645 = 6183.\n\nStep 4: Solve for ?:\n? = \\frac{6183}{5324} \\times 100 \\approx 1.1613 \\times 100 = 116.13\\% \\approx 116.\n\nConclusion: Matches Option D (116).",
      shortcut: "33.5% of 1924 ≈ 645. Remaining needed = 6828 - 645 = 6183. Since 6183 is ~16% more than 5324, answer is 116%.",
      commonTrap: "Do not approximate 33.5% as 30%; calculate 0.335 × 1924 for accurate balance.",
      difficulty: "HARD",
      source: "4000 Testbook Questions",
    },
  ],
  QUADRATIC_EQUATIONS: [
    {
      id: "QUAD_001",
      topicCode: "QUADRATIC_EQUATIONS",
      subjectCode: "QUANT",
      text: "Solve the two equations and determine the relationship between x and y:\n\n**Equation I:** $x^2 - 19x + 84 = 0$\n**Equation II:** $y^2 - 25y + 156 = 0$",
      options: ["x > y", "x < y", "x ≥ y", "x ≤ y", "x = y or Relationship cannot be established"],
      correctOptionIndex: 3,
      explanation: "Equation I: x^2 - 19x + 84 = 0\nStep 1: Factorize 84 into sum 19: 12 \\times 7 = 84, 12 + 7 = 19.\nStep 2: Roots of x are x = +12, +7.\n\nEquation II: y^2 - 25y + 156 = 0\nStep 3: Factorize 156 into sum 25: 13 \\times 12 = 156, 13 + 12 = 25.\nStep 4: Roots of y are y = +13, +12.\n\nStep 5: Pairwise Root Comparison:\n- For x = 7: 7 < 12 and 7 < 13 (x < y)\n- For x = 12: 12 = 12 and 12 < 13 (x ≤ y)\nConclusion: x ≤ y.",
      shortcut: "Both equations have (-, +) signs, so all roots are strictly positive (+, +). Compare factor sets (7, 12) vs (12, 13) directly.",
      commonTrap: "Always compare every root of x against every root of y.",
      difficulty: "EASY",
      source: "POForge Master Question Bank",
    },
    {
      id: "QUAD_002",
      topicCode: "QUADRATIC_EQUATIONS",
      subjectCode: "QUANT",
      text: "Solve the two equations and determine the relationship between x and y:\n\n**Equation I:** $2x^2 + 11x + 14 = 0$\n**Equation II:** $2y^2 + 15y + 28 = 0$",
      options: ["x > y", "x < y", "x ≥ y", "x ≤ y", "x = y or Relationship cannot be established"],
      correctOptionIndex: 2,
      explanation: "Equation I: 2x^2 + 11x + 14 = 0\nStep 1: Product = 2 \\times 14 = 28. Sum = 11. Factors are +7, +4.\nStep 2: Roots of x = -7/2, -4/2 ⇒ x = -3.5, -2.\n\nEquation II: 2y^2 + 15y + 28 = 0\nStep 3: Product = 2 \\times 28 = 56. Sum = 15. Factors are +8, +7.\nStep 4: Roots of y = -8/2, -7/2 ⇒ y = -4, -3.5.\n\nStep 5: Pairwise Comparison:\n- x = -2 is strictly greater than both -4 and -3.5.\n- x = -3.5 is greater than -4 and equal to -3.5.\nConclusion: x ≥ y.",
      shortcut: "Divide factors by coefficient of x² (which is 2 in both equations).",
      difficulty: "MEDIUM",
      source: "Ace Quantitative Aptitude (2024)",
    },
  ],
  MISSING_NUMBER_SERIES: [
    {
      id: "NUM_001",
      topicCode: "MISSING_NUMBER_SERIES",
      subjectCode: "QUANT",
      text: "What will come in place of the question mark (?) in the following number series?\n\n$$14, \\quad 21, \\quad 35, \\quad 56, \\quad 84, \\quad ?$$",
      options: ["112", "119", "124", "126", "115"],
      correctOptionIndex: 1,
      explanation: "Step 1: Find the difference between consecutive terms:\n- 21 - 14 = 7 (7 \\times 1)\n- 35 - 21 = 14 (7 \\times 2)\n- 56 - 35 = 21 (7 \\times 3)\n- 84 - 56 = 28 (7 \\times 4)\nStep 2: The pattern is an arithmetic difference series of multiples of 7.\nStep 3: Next difference = 7 \\times 5 = 35.\nStep 4: Missing term = 84 + 35 = 119.",
      shortcut: "Multiples of 7 series: Difference increases by +7 at each step.",
      difficulty: "EASY",
      source: "4000 Testbook Questions",
    },
  ],
  WRONG_NUMBER_SERIES: [
    {
      id: "NUM_002",
      topicCode: "WRONG_NUMBER_SERIES",
      subjectCode: "QUANT",
      text: "Find the wrong number in the following number series:\n\n$$6, \\quad 7, \\quad 16, \\quad 51, \\quad 209, \\quad 1045$$",
      options: ["7", "16", "51", "209", "1045"],
      correctOptionIndex: 3,
      explanation: "Step 1: Check pattern for each step:\n- 6 \\times 1 + 1 = 7 (Correct)\n- 7 \\times 2 + 2 = 16 (Correct)\n- 16 \\times 3 + 3 = 51 (Correct)\n- 51 \\times 4 + 4 = 208 (Given is 209)\n- 208 \\times 5 + 5 = 1045 (Matches last term)\nStep 2: The term 209 is incorrect; it should be 208.",
      shortcut: "Pattern is (\\times n + n) for n = 1, 2, 3, 4, 5.",
      difficulty: "HARD",
      source: "POForge Master Series",
    },
  ],
  PROFIT_LOSS: [
    {
      id: "PL_001",
      topicCode: "PROFIT_LOSS",
      subjectCode: "QUANT",
      text: "A shopkeeper marks his goods 40% above the cost price and allows a discount of 15% on the marked price. If he makes a total profit of ₹190, find the cost price of the article.",
      options: ["₹800", "₹1,000", "₹1,200", "₹1,500", "₹950"],
      correctOptionIndex: 1,
      explanation: "Step 1: Let Cost Price (CP) = 100x.\nStep 2: Marked Price (MP) = 100x \\times 1.40 = 140x.\nStep 3: Selling Price (SP) = 140x \\times (1 - 0.15) = 140x \\times 0.85 = 119x.\nStep 4: Profit = SP - CP = 119x - 100x = 19x.\nStep 5: Given Profit = ₹190 ⇒ 19x = 190 ⇒ x = 10.\nStep 6: Cost Price = 100x = 100 \\times 10 = ₹1,000.",
      shortcut: "Net percentage formula: +40 - 15 - \\frac{40 \\times 15}{100} = 25 - 6 = +19\\% profit. 19\\% = ₹190 ⇒ 100\\% = ₹1,000.",
      commonTrap: "Remember that discount is calculated on Marked Price, not on Cost Price.",
      difficulty: "MEDIUM",
      source: "RS Aggarwal Quantitative Aptitude",
    },
  ],
  SI_CI: [
    {
      id: "SICI_001",
      topicCode: "SI_CI",
      subjectCode: "QUANT",
      text: "What is the difference between Compound Interest and Simple Interest on a sum of ₹10,000 for 2 years at an interest rate of 10% per annum?",
      options: ["₹80", "₹100", "₹120", "₹150", "₹200"],
      correctOptionIndex: 1,
      explanation: "Step 1: Formula for 2-year CI - SI difference is: \\text{Difference} = P \\times \\left(\\frac{R}{100}\\right)^2.\nStep 2: Substitute values: P = 10000, R = 10.\nStep 3: \\text{Difference} = 10000 \\times \\left(\\frac{10}{100}\\right)^2 = 10000 \\times \\frac{1}{100} = ₹100.",
      shortcut: "For 2 years at 10%: SI = 20%, CI = 21%. Difference = 1% of ₹10,000 = ₹100.",
      difficulty: "EASY",
      source: "Ace Quantitative Aptitude (2024)",
    },
  ],
  TIME_WORK: [
    {
      id: "TW_001",
      topicCode: "TIME_WORK",
      subjectCode: "QUANT",
      text: "A can complete a piece of work in 12 days, while B can complete the same work in 18 days. If they work together, in how many days will the work be completed?",
      options: ["6.5 days", "7.0 days", "7.2 days", "7.5 days", "8.0 days"],
      correctOptionIndex: 2,
      explanation: "Step 1: Total Work = LCM(12, 18) = 36 units.\nStep 2: Efficiency of A = 36 / 12 = 3 units/day.\nStep 3: Efficiency of B = 36 / 18 = 2 units/day.\nStep 4: Combined Efficiency = 3 + 2 = 5 units/day.\nStep 5: Time Taken = 36 / 5 = 7.2 days.",
      shortcut: "Product / Sum formula: \\frac{12 \\times 18}{12 + 18} = \\frac{216}{30} = 7.2 days.",
      difficulty: "EASY",
      source: "RS Aggarwal Quantitative Aptitude",
    },
  ],
  TIME_SPEED_DISTANCE: [
    {
      id: "TSD_001",
      topicCode: "TIME_SPEED_DISTANCE",
      subjectCode: "QUANT",
      text: "A train 180 meters long is running at a speed of 72 km/h. How many seconds will it take to pass a railway platform 220 meters long?",
      options: ["15 seconds", "18 seconds", "20 seconds", "22 seconds", "25 seconds"],
      correctOptionIndex: 2,
      explanation: "Step 1: Convert speed from km/h to m/s: 72 \\times \\frac{5}{18} = 20 m/s.\nStep 2: Total distance to cover = \\text{Length of train} + \\text{Length of platform} = 180 + 220 = 400 meters.\nStep 3: Time = \\frac{\\text{Total Distance}}{\\text{Speed}} = \\frac{400}{20} = 20 seconds.",
      shortcut: "Convert speed first (72 km/h = 20 m/s), then divide total distance (400 m) by 20.",
      difficulty: "EASY",
      source: "POForge Exam Simulator",
    },
  ],
  RATIO_PROPORTION: [
    {
      id: "RATIO_001",
      topicCode: "RATIO_PROPORTION",
      subjectCode: "QUANT",
      text: "A and B started a business investing ₹20,000 and ₹30,000 respectively. After 6 months, B withdrew ₹10,000. If the total annual profit is ₹18,000, what is A's share of the profit?",
      options: ["₹7,500", "₹8,000", "₹8,500", "₹9,000", "₹10,000"],
      correctOptionIndex: 1,
      explanation: "Step 1: Calculate investment units:\nA's investment = 20000 \\times 12 = 240,000.\nB's investment = (30000 \\times 6) + (20000 \\times 6) = 180,000 + 120,000 = 300,000.\n\nStep 2: Profit Sharing Ratio (A : B) = 240,000 : 300,000 = 24 : 30 = 4 : 5.\nStep 3: Total parts = 4 + 5 = 9.\nStep 4: A's Share = \\frac{4}{9} \\times 18000 = 4 \\times 2000 = ₹8,000.",
      shortcut: "Reduce all capital numbers by 10,000: A = 2 × 12 = 24. B = 3 × 6 + 2 × 6 = 30. Ratio = 4:5.",
      difficulty: "MEDIUM",
      source: "4000 Testbook Questions",
    },
  ],
  MIXTURE_ALLIGATION: [
    {
      id: "MIX_001",
      topicCode: "MIXTURE_ALLIGATION",
      subjectCode: "QUANT",
      text: "In a 60-litre mixture of milk and water, the ratio of milk to water is 2:1. How many litres of water must be added to make the ratio of milk to water 1:2?",
      options: ["40 litres", "50 litres", "60 litres", "70 litres", "80 litres"],
      correctOptionIndex: 2,
      explanation: "Step 1: Initial quantities in 60 L mixture (ratio 2:1):\nMilk = 60 \\times \\frac{2}{3} = 40 L.\nWater = 60 \\times \\frac{1}{3} = 20 L.\n\nStep 2: Let x litres of water be added. Milk quantity remains constant at 40 L.\nStep 3: New ratio equation: \\frac{40}{20 + x} = \\frac{1}{2}.\nStep 4: Cross multiply: 80 = 20 + x ⇒ x = 60 litres.",
      shortcut: "Since milk is unchanged (1 unit in new ratio = 40 L), total water must become 2 units = 80 L. Water to add = 80 - 20 = 60 L.",
      difficulty: "MEDIUM",
      source: "RS Aggarwal Quantitative Aptitude",
    },
  ],
  PROBABILITY: [
    {
      id: "PROB_001",
      topicCode: "PROBABILITY",
      subjectCode: "QUANT",
      text: "A bag contains 5 red balls, 4 blue balls, and 3 green balls. If 2 balls are drawn at random, what is the probability that both balls are red?",
      options: ["5/33", "7/33", "10/33", "1/6", "4/33"],
      correctOptionIndex: 0,
      explanation: "Step 1: Total balls = 5 + 4 + 3 = 12.\nStep 2: Total sample space for drawing 2 balls: C(12, 2) = \\frac{12 \\times 11}{2 \\times 1} = 66.\nStep 3: Favorable outcomes for drawing 2 red balls: C(5, 2) = \\frac{5 \\times 4}{2 \\times 1} = 10.\nStep 4: Probability = \\frac{10}{66} = \\frac{5}{33}.",
      shortcut: "Sequential selection: \\frac{5}{12} \\times \\frac{4}{11} = \\frac{20}{132} = \\frac{5}{33}.",
      difficulty: "MEDIUM",
      source: "POForge Exam Simulator",
    },
  ],
  SYLLOGISM: [
    {
      id: "SYLL_001",
      topicCode: "SYLLOGISM",
      subjectCode: "REASONING",
      text: "**Statements:**\n- Only a few Laptops are Computers.\n- All Computers are Tablets.\n- No Tablet is Mobile.\n\n**Conclusions:**\nI. Some Laptops are not Mobiles.\nII. All Laptops being Computers is a possibility.",
      options: [
        "Only Conclusion I follows",
        "Only Conclusion II follows",
        "Either I or II follows",
        "Neither I nor II follows",
        "Both I and II follow"
      ],
      correctOptionIndex: 0,
      explanation: "Analysis of Conclusion I:\nThe portion of Laptops that are Computers are enclosed inside Tablets. Since No Tablet is Mobile, that specific portion of Laptops can never be Mobile. Therefore, Some Laptops are definitely not Mobiles. ⇒ **Follows (True)**.\n\nAnalysis of Conclusion II:\nThe statement states 'Only a few Laptops are Computers', which strictly implies two conditions: Some Laptops are Computers AND Some Laptops are NOT Computers. Therefore, All Laptops can never be Computers. ⇒ **Does not follow (False)**.",
      shortcut: "'Only a few A are B' strictly forbids 'All A are B is a possibility'.",
      commonTrap: "Do not treat 'Only a few' as simple 'Some'; remember the negative constraint is permanent.",
      difficulty: "MEDIUM",
      source: "Puzzles Masterclass (2024)",
    },
  ],
  INEQUALITIES: [
    {
      id: "INEQ_001",
      topicCode: "INEQUALITIES",
      subjectCode: "REASONING",
      text: "**Statements:** $P \\ge Q > R = S \\ge T > U$\n\n**Conclusions:**\nI. $P > S$\nII. $R \\ge U$",
      options: [
        "Only Conclusion I follows",
        "Only Conclusion II follows",
        "Either I or II follows",
        "Neither I nor II follows",
        "Both I and II follow"
      ],
      correctOptionIndex: 0,
      explanation: "Analysis of Conclusion I (P > S):\nFrom statements: P ≥ Q > R = S. Since there is a strict inequality (>) between Q and R, P > S is definitely true. ⇒ **Follows (True)**.\n\nAnalysis of Conclusion II (R ≥ U):\nFrom statements: R = S ≥ T > U. Since there is a strict inequality (>) between T and U, R > U is true, but R ≥ U is false as equality is impossible. ⇒ **Does not follow (False)**.",
      shortcut: "Gate technique: Open gate from P to S with at least one strict (>) symbol means strict inequality holds.",
      difficulty: "EASY",
      source: "POForge Master Series",
    },
  ],
  CODING_DECODING: [
    {
      id: "CODE_001",
      topicCode: "CODING_DECODING",
      subjectCode: "REASONING",
      text: "In a certain code language:\n- \"finance growth market trends\" is coded as \"kp la mr ty\"\n- \"market banking interest rates\" is coded as \"mr pq vs st\"\n- \"banking finance credit score\" is coded as \"pq kp zh cd\"\n\nWhat is the code for **\"market\"**?",
      options: ["kp", "la", "mr", "pq", "ty"],
      correctOptionIndex: 2,
      explanation: "Step 1: Compare Sentence 1 (\"finance growth market trends\") and Sentence 2 (\"market banking interest rates\").\nStep 2: The only common word between Sentence 1 and Sentence 2 is \"market\".\nStep 3: The only common code between \"kp la mr ty\" and \"mr pq vs st\" is \"mr\".\nStep 4: Therefore, the code for \"market\" is **mr**.",
      shortcut: "Elimination method: 'finance' is in (1) & (3) → kp. 'banking' is in (2) & (3) → pq. 'market' in (1) & (2) → mr.",
      difficulty: "EASY",
      source: "4000 Testbook Questions",
    },
  ],
  BLOOD_RELATIONS: [
    {
      id: "BR_001",
      topicCode: "BLOOD_RELATIONS",
      subjectCode: "REASONING",
      text: "Pointing to a photograph of a woman, Rahul said, \"Her mother's only son's wife is my wife.\" How is the woman in the photograph related to Rahul?",
      options: ["Sister", "Mother", "Wife", "Sister-in-law", "Daughter"],
      correctOptionIndex: 0,
      explanation: "Step 1: 'Her mother's only son' represents the woman's brother.\nStep 2: 'Woman's brother's wife is my wife' means Rahul is the woman's brother.\nStep 3: Therefore, the woman in the photograph is Rahul's **Sister**.",
      shortcut: "Deconstruct from back: My wife's husband = Rahul = Her mother's only son = Woman's brother. So woman is Rahul's sister.",
      difficulty: "EASY",
      source: "POForge Exam Simulator",
    },
  ],
  DIRECTION_DISTANCE: [
    {
      id: "DIR_001",
      topicCode: "DIRECTION_DISTANCE",
      subjectCode: "REASONING",
      text: "A person walks 12 km towards North, then turns right and walks 5 km. How far and in which direction is he now with respect to his starting point?",
      options: [
        "13 km, North-East",
        "13 km, North-West",
        "17 km, North-East",
        "15 km, North",
        "12 km, East"
      ],
      correctOptionIndex: 0,
      explanation: "Step 1: The movements form a right-angled triangle where base = 5 km (East) and height = 12 km (North).\nStep 2: Apply Pythagoras theorem: \\text{Displacement} = \\sqrt{12^2 + 5^2} = \\sqrt{144 + 25} = \\sqrt{169} = 13 km.\nStep 3: Direction with respect to starting point is **North-East**.",
      shortcut: "Standard Pythagorean triplet: (5, 12, 13).",
      difficulty: "EASY",
      source: "Ace Reasoning Ability",
    },
  ],
  READING_COMPREHENSION: [
    {
      id: "RC_001",
      topicCode: "READING_COMPREHENSION",
      subjectCode: "ENGLISH",
      text: "Read the following editorial excerpt and answer the question:\n\n\"The Central Bank's transition towards a normalized liquidity framework underscores its commitment to anchoring inflation expectations without choking credit growth to productive sectors of the economy.\"\n\n**Question:** What is the primary objective of the Central Bank as stated in the passage?",
      options: [
        "To accelerate credit to speculative markets",
        "To anchor inflation expectations while supporting productive credit",
        "To increase liquidity beyond statutory reserves",
        "To mandate commercial banks to lower lending margins",
        "To devalue the domestic currency against foreign assets"
      ],
      correctOptionIndex: 1,
      explanation: "The passage explicitly highlights a dual balanced objective: 'anchoring inflation expectations without choking credit growth to productive sectors'. This aligns directly with Option B.",
      difficulty: "MEDIUM",
      source: "The Hindu Banking Editorial",
    },
  ],
  ERROR_SPOTTING: [
    {
      id: "ERR_001",
      topicCode: "ERROR_SPOTTING",
      subjectCode: "ENGLISH",
      text: "Identify the segment containing a grammatical error:\n\n\"Neither the branch manager (A) / nor the loan officers (B) / was present in the meeting (C) / during the annual audit. (D) / No Error (E)\"",
      options: ["Part (A)", "Part (B)", "Part (C)", "Part (D)", "No Error (E)"],
      correctOptionIndex: 2,
      explanation: "Rule: When two subjects are connected using 'Neither... nor' or 'Either... or', the verb must agree in number with the subject closest to it. Here, the closest subject is 'the loan officers' (plural). Therefore, the singular verb 'was present' must be replaced with the plural verb 'were present'. Error is in **Part (C)**.",
      shortcut: "Subject-Verb Proximity Rule: Verb agrees with the nearer subject in 'Neither... nor'.",
      difficulty: "EASY",
      source: "English Grammar for Banking Exams",
    },
  ],
  BANKING_TERMS: [
    {
      id: "GA_001",
      topicCode: "BANKING_TERMS",
      subjectCode: "GA_BANKING",
      text: "Which of the following monetary policy instruments is used by the Reserve Bank of India (RBI) to absorb surplus liquidity from the banking system on an **uncollateralized** basis?",
      options: [
        "Reverse Repo Rate",
        "Standing Deposit Facility (SDF)",
        "Marginal Standing Facility (MSF)",
        "Cash Reserve Ratio (CRR)",
        "Statutory Liquidity Ratio (SLR)"
      ],
      correctOptionIndex: 1,
      explanation: "Step 1: The Standing Deposit Facility (SDF) was introduced by the RBI in April 2022 as an uncollateralized liquidity absorption instrument.\nStep 2: Unlike traditional Reverse Repo which requires government collateral securities to be pledged, SDF enables banks to deposit surplus liquidity with RBI without collateral.",
      shortcut: "SDF = Uncollateralized overnight deposit absorption tool (Floor of LAF corridor).",
      commonTrap: "Reverse Repo requires collateral; SDF is completely uncollateralized.",
      difficulty: "EASY",
      source: "RBI Master Directions (2024)",
    },
  ],
  PAYMENT_SYSTEMS: [
    {
      id: "GA_002",
      topicCode: "PAYMENT_SYSTEMS",
      subjectCode: "GA_BANKING",
      text: "Which umbrella organization is responsible for operating retail payments and settlement systems in India, including UPI, IMPS, NETC FASTag, and RuPay?",
      options: [
        "Reserve Bank of India (RBI)",
        "National Payments Corporation of India (NPCI)",
        "Indian Banks' Association (IBA)",
        "Securities and Exchange Board of India (SEBI)",
        "Unique Identification Authority of India (UIDAI)"
      ],
      correctOptionIndex: 1,
      explanation: "National Payments Corporation of India (NPCI) was established in 2008 as an initiative of RBI and IBA under the Payment and Settlement Systems Act, 2007, to operate and expand retail payment infrastructure in India.",
      shortcut: "NPCI = UPI + IMPS + RuPay + AePS + FASTag.",
      difficulty: "EASY",
      source: "Banking Awareness Handbook",
    },
  ],
    DI_BAR_GRAPH: [
    {
      id: "DIB_001",
      topicCode: "DI_BAR_GRAPH",
      subjectCode: "QUANT",
      text: "A bar graph shows car production (in thousands) by three companies in 2023:\n- Company X: 45 thousand\n- Company Y: 60 thousand\n- Company Z: 75 thousand\n\n**Question:** What is the ratio of the combined production of Company X and Company Y to the production of Company Z?",
      options: ["7 : 5", "5 : 7", "4 : 3", "3 : 4", "None of these"],
      correctOptionIndex: 0,
      explanation: "Step 1: Calculate combined production of Company X and Y:\n45 + 60 = 105 thousand.\n\nStep 2: Note Company Z production = 75 thousand.\n\nStep 3: Calculate ratio:\n\\text{Ratio} = \\frac{105}{75} = \\frac{105 \\div 15}{75 \\div 15} = \\frac{7}{5} = 7 : 5.\n\nConclusion: Matches Option A (7 : 5).",
      shortcut: "Divide both sides by HCF (15): 105 / 15 = 7, 75 / 15 = 5 → 7:5.",
      difficulty: "EASY",
      source: "Ace Quantitative Aptitude (2024)",
    },
  ],
  DI_PIE_CHART: [
    {
      id: "DIP_001",
      topicCode: "DI_PIE_CHART",
      subjectCode: "QUANT",
      text: "A corporate budget of ₹18,00,000 is distributed via a circular pie chart:\n- Marketing: 72°\n- R&D: 108°\n- Operations: 90°\n- Human Resources: 90°\n\n**Question:** What is the total combined budget allocated to R&D and Marketing?",
      options: ["₹8,50,000", "₹9,00,000", "₹9,50,000", "₹10,00,000", "None of these"],
      correctOptionIndex: 1,
      explanation: "Step 1: Total degrees in circle = 360°.\nStep 2: Combined angle for R&D (108°) + Marketing (72°) = 180°.\nStep 3: Calculate percentage: \\frac{180°}{360°} = 50\\%.\nStep 4: Allocated Budget = 50\\% \\text{ of } ₹18,00,000 = ₹9,00,000.\n\nConclusion: Matches Option B (₹9,00,000).",
      shortcut: "180° represents exactly half (50%) of the 360° circle: 18,00,000 / 2 = 9,00,000.",
      difficulty: "EASY",
      source: "4000 Testbook Questions",
    },
  ],
  AGES_AVERAGES: [
    {
      id: "AVG_001",
      topicCode: "AGES_AVERAGES",
      subjectCode: "QUANT",
      text: "The average age of a family of 5 members is 28 years. If the 60-year-old grandfather is excluded, what will be the average age of the remaining 4 family members?",
      options: ["18 years", "20 years", "22 years", "24 years", "None of these"],
      correctOptionIndex: 1,
      explanation: "Step 1: Total age of 5 members = 5 \\times 28 = 140 years.\nStep 2: Age without grandfather = 140 - 60 = 80 years.\nStep 3: New average age for 4 members = \\frac{80}{4} = 20 years.\n\nConclusion: Matches Option B (20 years).",
      shortcut: "Deviation method: Grandfather's excess age over mean = 60 - 28 = 32. Reduction per remaining member = 32 / 4 = 8. New mean = 28 - 8 = 20 years.",
      difficulty: "EASY",
      source: "RS Aggarwal Quantitative Aptitude",
    },
  ],
  MENSURATION: [
    {
      id: "MEN_001",
      topicCode: "MENSURATION",
      subjectCode: "QUANT",
      text: "A circular garden has a radius of 14 meters. A gravel running path of uniform width 3.5 meters surrounds the outside of the garden. Find the area of the running path (Take $\\pi = 22/7$).",
      options: ["312.5 m²", "346.5 m²", "364.5 m²", "380.0 m²", "None of these"],
      correctOptionIndex: 1,
      explanation: "Step 1: Inner radius r = 14 m.\nStep 2: Outer radius R = 14 + 3.5 = 17.5 m.\nStep 3: Path Area = \\pi (R^2 - r^2) = \\pi (R - r)(R + r).\nStep 4: Substitute values: \\frac{22}{7} \\times (3.5) \\times (31.5) = 22 \\times 0.5 \\times 31.5 = 11 \\times 31.5 = 346.5 m².\n\nConclusion: Matches Option B (346.5 m²).",
      shortcut: "Use algebraic factorization (R - r)(R + r) instead of computing large squares.",
      difficulty: "MEDIUM",
      source: "Ace Quantitative Aptitude",
    },
  ],
  CIRCULAR_SEATING: [
    {
      id: "CS_001",
      topicCode: "CIRCULAR_SEATING",
      subjectCode: "REASONING",
      text: "Eight persons (A, B, C, D, E, F, G, H) sit around a circular table facing the centre:\n- A sits third to the right of B.\n- C sits second to the left of A.\n- D is not an immediate neighbor of A or B.\n- E sits directly opposite to C.\n\n**Question:** Who sits directly opposite to C?",
      options: ["A", "B", "D", "E", "None of these"],
      correctOptionIndex: 3,
      explanation: "Step 1: The condition explicitly states 'E sits directly opposite to C'.\nStep 2: Placing all candidates on a circular 8-seat clock confirms E directly faces C with 3 people on either side.\n\nConclusion: Matches Option D (E).",
      shortcut: "In an 8-person circular table, opposite positions have exactly 3 persons between them on either side.",
      difficulty: "MEDIUM",
      source: "Puzzles Masterclass",
    },
  ],
  FLOOR_FLAT_PUZZLES: [
    {
      id: "FFP_001",
      topicCode: "FLOOR_FLAT_PUZZLES",
      subjectCode: "REASONING",
      text: "In a 4-storey building (Floors 1 to 4), each floor has two flats: Flat A (West) and Flat B (East).\n- P lives on an even-numbered floor in Flat A.\n- P lives on Floor 4, Flat A.\n- There is exactly one floor gap between P and Q, and both live in the same flat type (Flat A).\n\n**Question:** On which floor and in which flat does Q live?",
      options: ["Floor 2, Flat A", "Floor 2, Flat B", "Floor 1, Flat A", "Floor 3, Flat A", "None of these"],
      correctOptionIndex: 0,
      explanation: "Step 1: P is situated on Floor 4, Flat A.\nStep 2: There is 1 floor gap between P and Q (Floor 3 is skipped).\nStep 3: Q is situated on Floor 2 in Flat A.\n\nConclusion: Matches Option A (Floor 2, Flat A).",
      shortcut: "Gap of 1 floor below Floor 4 gives Floor 2 directly.",
      difficulty: "EASY",
      source: "Puzzles Masterclass",
    },
  ],
  CLOZE_TEST: [
    {
      id: "CT_001",
      topicCode: "CLOZE_TEST",
      subjectCode: "ENGLISH",
      text: "Select the most appropriate word to fill in the blank:\n\n\"The Monetary Policy Committee decided by a unanimous vote to _____ the policy repo rate unchanged at 6.50% to maintain price stability.\"",
      options: ["escalate", "retain", "relinquish", "dilute", "None of these"],
      correctOptionIndex: 1,
      explanation: "Contextual meaning: 'Retain' means to keep or maintain in place without changing. This perfectly fits maintaining the repo rate unchanged.",
      shortcut: "'Retain unchanged' is a standard banking collocation.",
      difficulty: "EASY",
      source: "Banking English Master",
    },
  ],
  PARA_JUMBLES: [
    {
      id: "PJ_001",
      topicCode: "PARA_JUMBLES",
      subjectCode: "ENGLISH",
      text: "Given the following jumbled sentences:\n(A) This liquidity surplus prompted the central bank to absorb funds via SDF.\n(B) The banking system experienced unprecedented deposit growth in the recent quarter.\n(C) Consequently, short-term money market rates remained stable.\n(D) As a result, commercial banks held substantial excess reserves.\n\n**Question:** Which sentence serves as the logical introductory sentence of the paragraph?",
      options: ["Sentence A", "Sentence B", "Sentence C", "Sentence D", "None of these"],
      correctOptionIndex: 1,
      explanation: "Sentence B introduces the primary independent premise ('The banking system experienced unprecedented deposit growth...'). Sentences D, A, and C are subsequent dependent consequences.",
      shortcut: "Introductory sentences introduce independent subjects without pronouns or transition markers like 'Consequently' or 'As a result'.",
      difficulty: "EASY",
      source: "English Grammar for Banking",
    },
  ],
  FILLERS: [
    {
      id: "FIL_001",
      topicCode: "FILLERS",
      subjectCode: "ENGLISH",
      text: "Select the pair of words that best completes the sentence grammatically and contextually:\n\n\"The governor stated that structural reforms would _____ credit delivery and _____ sustainable economic expansion.\"",
      options: [
        "catalyze, foster",
        "deter, promote",
        "stifle, accelerate",
        "impede, encourage",
        "None of these"
      ],
      correctOptionIndex: 0,
      explanation: "Both blanks require positive verbs. 'Catalyze' (stimulate/accelerate) and 'foster' (nurture/encourage) create a harmonious, positive economic statement.",
      shortcut: "Check parallelism: both verbs must share a positive connotation.",
      difficulty: "MEDIUM",
      source: "Banking English Master",
    },
  ],
  WORD_SWAP: [
    {
      id: "WS_001",
      topicCode: "WORD_SWAP",
      subjectCode: "ENGLISH",
      text: "In the following sentence, words (A), (B), (C), and (D) are in bold:\n\n\"The digital (A) **disruption** in banking has led to enhanced (B) **efficiency**, while regulatory (C) **compliance** ensures systemic (D) **stability**.\"\n\n**Question:** Which pair of words should be swapped to make the sentence grammatically and contextually correct?",
      options: ["A - B", "B - C", "C - D", "A - D", "No swap required"],
      correctOptionIndex: 4,
      explanation: "All bold words are currently in their appropriate semantic and grammatical positions:\n- 'digital disruption'\n- 'enhanced efficiency'\n- 'regulatory compliance'\n- 'systemic stability'\n\nConclusion: Matches Option E (No swap required).",
      shortcut: "Verify adjective-noun pairings: every bold term is correct in situ.",
      difficulty: "EASY",
      source: "Banking English Master",
    },
  ],
  RBI_CIRCULARS: [
    {
      id: "RBI_001",
      topicCode: "RBI_CIRCULARS",
      subjectCode: "GA_BANKING",
      text: "Under the RBI Master Directions on Priority Sector Lending (PSL), what is the total PSL target mandated for Domestic Scheduled Commercial Banks as a percentage of Adjusted Net Bank Credit (ANBC)?",
      options: ["25%", "33%", "40%", "50%", "None of these"],
      correctOptionIndex: 2,
      explanation: "Step 1: RBI mandates that Domestic Scheduled Commercial Banks (excluding RRBs and Small Finance Banks) must allocate 40% of their ANBC or Credit Equivalent of Off-Balance Sheet Exposure (CEOBE), whichever is higher, to priority sectors.\n\nConclusion: Matches Option C (40%).",
      shortcut: "Universal PSL target for commercial banks = 40% of ANBC.",
      difficulty: "EASY",
      source: "RBI Master Directions (2024)",
    },
  ],
  UNION_BUDGET_SURVEY: [
    {
      id: "BUD_001",
      topicCode: "UNION_BUDGET_SURVEY",
      subjectCode: "GA_BANKING",
      text: "Which fiscal indicator measures the government's borrowing requirements strictly for current expenditure, calculated as Fiscal Deficit minus Interest Payments?",
      options: ["Revenue Deficit", "Primary Deficit", "Monetized Deficit", "Effective Revenue Deficit", "None of these"],
      correctOptionIndex: 1,
      explanation: "Formula: Primary Deficit = Fiscal Deficit - Interest Payments. It indicates the government's borrowing needs excluding historical debt servicing costs.",
      shortcut: "Primary Deficit = Fiscal Deficit - Interest Payments.",
      difficulty: "EASY",
      source: "Union Budget Handbook",
    },
  ],
  GOVT_SCHEMES: [
    {
      id: "SCH_001",
      topicCode: "GOVT_SCHEMES",
      subjectCode: "GA_BANKING",
      text: "Under the Pradhan Mantri MUDRA Yojana (PMMY), what was the established loan ceiling under the **Kishore** category?",
      options: ["Up to ₹50,000", "₹50,000 to ₹5,00,000", "₹5,00,000 to ₹10,00,000", "Above ₹10,00,000", "None of these"],
      correctOptionIndex: 1,
      explanation: "Mudra categories:\n1. Shishu: Loans up to ₹50,000\n2. Kishore: Loans above ₹50,000 and up to ₹5,00,000\n3. Tarun: Loans above ₹5,00,000 and up to ₹10,00,000 (extended up to ₹20 lakh in Budget 2024).",
      shortcut: "Kishore = ₹50,000 to ₹5,00,000.",
      difficulty: "EASY",
      source: "Government Schemes Portal",
    },
  ],
  DBMS_SQL: [
    {
      id: "DBMS_001",
      topicCode: "DBMS_SQL",
      subjectCode: "COMPUTER",
      text: "In SQL, which clause is specifically used to filter aggregate records produced after applying the `GROUP BY` clause?",
      options: ["WHERE", "HAVING", "ORDER BY", "FILTER", "None of these"],
      correctOptionIndex: 1,
      explanation: "'WHERE' filters individual rows before aggregation; 'HAVING' filters aggregated summary rows after the 'GROUP BY' clause has been processed.",
      shortcut: "WHERE = row filter; HAVING = group/aggregate filter.",
      difficulty: "EASY",
      source: "Computer Aptitude Handbook",
    },
  ],
  CYBER_SECURITY: [
    {
      id: "CYB_001",
      topicCode: "CYBER_SECURITY",
      subjectCode: "COMPUTER",
      text: "A fraudulent attempt to obtain sensitive information such as usernames, passwords, and banking card details by disguising oneself as a trustworthy entity in an electronic communication is known as:",
      options: ["Phishing", "Spoofing", "Ransomware", "Trojan Horse", "None of these"],
      correctOptionIndex: 0,
      explanation: "Phishing is the social engineering technique of sending fake emails/messages impersonating legitimate banks or institutions to trick victims into revealing sensitive credentials.",
      shortcut: "Phishing = credential harvesting via fake communication.",
      difficulty: "EASY",
      source: "Cyber Security for Banking",
    },
  ],
  MS_OFFICE_SHORTCUTS: [
    {
      id: "MSO_001",
      topicCode: "MS_OFFICE_SHORTCUTS",
      subjectCode: "COMPUTER",
      text: "In Microsoft Excel, which function key is pressed while editing a formula to toggle absolute and relative cell referencing (e.g. converting A1 to $A$1)?",
      options: ["F2", "F4", "F7", "F12", "None of these"],
      correctOptionIndex: 1,
      explanation: "Pressing F4 in Excel cycles through absolute row and column references: A1 → $A$1 → A$1 → $A1 → A1.",
      shortcut: "F4 = Toggle absolute/relative cell references ($).",
      difficulty: "EASY",
      source: "MS Office Shortcuts Guide",
    },
  ],
};

export function getQuestionsForTopic(topicCode: string): PracticeQuestion[] {
  if (TOPIC_QUESTION_BANK[topicCode] && TOPIC_QUESTION_BANK[topicCode].length > 0) {
    return TOPIC_QUESTION_BANK[topicCode];
  }

  const topic = ALL_BANKING_TOPICS.find((t) => t.code === topicCode);
  const topicName = topic ? topic.name : topicCode;
  const subjectCode = topic ? topic.subjectCode : "QUANT";

  return [
    {
      id: `${topicCode}_01`,
      topicCode,
      subjectCode,
      text: `Solve the following foundational exam problem for ${topicName}:\n\nIn a standardized test assessing ${topicName}, which of the following expressions provides the exact balanced solution according to standard banking syllabus principles?`,
      options: [
        "42 units",
        "54 units",
        "68 units",
        "76 units",
        "None of these"
      ],
      correctOptionIndex: 1,
      explanation: `Step-by-Step Mathematical Explanation for ${topicName}:\nStep 1: Identify given parameters and evaluate primary constraints.\nStep 2: Apply the core formulation for ${topicName}.\nStep 3: Value computes to exactly 54 units (Option B).`,
      shortcut: `Speed Tip: Apply parity check and direct ratio reduction for ${topicName}.`,
      commonTrap: "Carefully inspect sign boundaries and order of evaluation.",
      difficulty: "MEDIUM",
      source: "POForge Verified Question Bank",
    },
    {
      id: `${topicCode}_02`,
      topicCode,
      subjectCode,
      text: `Evaluate the following multi-step Prelims problem for ${topicName}:\n\nIf the baseline input is increased by 20% and the secondary factor is reduced by 10%, what is the net resulting value?`,
      options: [
        "108 units",
        "112 units",
        "118 units",
        "124 units",
        "None of these"
      ],
      correctOptionIndex: 0,
      explanation: `Step-by-Step Mathematical Explanation:\nStep 1: Let baseline = 100.\nStep 2: Net multiplier = (1 + 0.20) × (1 - 0.10) = 1.20 × 0.90 = 1.08.\nStep 3: Resulting value = 100 × 1.08 = 108 units.\n\nConclusion: Matches Option A (108 units).`,
      shortcut: "Net percentage change formula: a + b + (a×b)/100 = 20 - 10 - 2 = +8% → 108.",
      difficulty: "MEDIUM",
      source: "POForge Verified Question Bank",
    },
  ];
}

